### ISSUE TITLE
Config Sanity Checking

### ISSUE THREAD

**Issue by basdxz** [FalsePattern/FalsePatternLib#11]
I feel like the configs are lacking in the sense of sanity checking, it would be nice to be able to set min/max values with configs and then on-save enforce that x value is not above y. Potential implementation could be in the form of a method in SimpleGuiConfig that allows the configs to be validated/modified before they are committed.

**Comment by FalsePattern** [comment]
The validation implementation has been added into the ConfigurationManager, and will also be done automatically when initializing a config, saving a config to a file (if the boolean argument is set to true), and syncing configs server->client.
This will be available in the upcoming 0.10 release

**Comment by FalsePattern** [comment]
Added in 0.10.0
