### ISSUE TITLE
Incompatibility Crash. It crashes upon loading up.

### ISSUE THREAD

**Issue by branman5949** [FalsePattern/FalsePatternLib#13]
[crash-2022-08-20_15.21.04-client.txt](https://github.com/FalsePattern/FalsePatternLib/files/9387912/crash-2022-08-20_15.21.04-client.txt)
[latest.log](https://github.com/FalsePattern/FalsePatternLib/files/9387914/latest.log)
[fml-client-latest.log](https://github.com/FalsePattern/FalsePatternLib/files/9387915/fml-client-latest.log)

**Comment by FalsePattern** [comment]
Fixed in 0.10.5
