### ISSUE TITLE
Weird Crash 

### ISSUE THREAD

**Issue by az201601** [FalsePattern/FalsePatternLib#14]
[crash-2022-08-21_21.11.35-client.txt](https://github.com/FalsePattern/FalsePatternLib/files/9388783/crash-2022-08-21_21.11.35-client.txt)

**Comment by FalsePattern** [comment]
try updating to 0.10.2

**Comment by az201601** [comment]
[crash-2022-08-23_20.09.25-client.txt](https://github.com/FalsePattern/FalsePatternLib/files/9400634/crash-2022-08-23_20.09.25-client.txt)

Updated to 0.10.2.. now getting this crash

**Comment by az201601** [comment]
0.10.4 still not working
[crash-2022-08-25_15.37.34-client.txt](https://github.com/FalsePattern/FalsePatternLib/files/9421160/crash-2022-08-25_15.37.34-client.txt)

**Comment by az201601** [comment]
seems to be fixed so far! thank you
