### ISSUE TITLE
GAME CRASHES IMMEDIATELY EVEN IF I ONLY ADD falsepatternlib-mc1.7.10-0.10.10.jar

### ISSUE THREAD

**Issue by iamsoNewBee** [FalsePattern/FalsePatternLib#17]
0.10.7 DOESNT LEAD TO CRASH

**Comment by FalsePattern** [comment]
Use GasStation instead of SpongeMixins

**Comment by FalsePattern** [comment]
Not enough information given, i cannot diagnose this. Post your `fml-client-latest.log`

**Comment by iamsoNewBee** [comment]
[crash-2022-09-18_20.33.18-client.txt](https://github.com/FalsePattern/FalsePatternLib/files/9593979/crash-2022-09-18_20.33.18-client.txt)
HERE U GO

**Comment by FalsePattern** [comment]
wrong file, i need the `fml-client-latest.log` file.

**Comment by iamsoNewBee** [comment]
[latest.log](https://github.com/FalsePattern/FalsePatternLib/files/9593982/latest.log)
THIS?

**Comment by quentin452** [comment]
fml-client-latest.log

**Comment by quentin452** [comment]
or give the mods list

**Comment by iamsoNewBee** [comment]
> 或提供模组列表
falsepatternlib-mc1.7.10-0.10.10.jar is the only mod

**Comment by FalsePattern** [comment]
![this](https://user-images.githubusercontent.com/30945458/190902604-3d0ed4b4-18d9-4720-b4d6-38286e6fe1f9.png)

**Comment by iamsoNewBee** [comment]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/98573273/190902840-0b0b06d7-de33-4ead-8d82-29c7d89030f3.png">
IS THIS THE RIGHT FLODER? I DONT THINK IT HAS GENERATED

**Comment by iamsoNewBee** [comment]
[minecraft-exported-crash-info-2022-09-18T20-43-21.zip](https://github.com/FalsePattern/FalsePatternLib/files/9594001/minecraft-exported-crash-info-2022-09-18T20-43-21.zip)
THIS MAY HELP?

**Comment by quentin452** [comment]
what minecraft launcher do you use?

**Comment by iamsoNewBee** [comment]
> what minecraft launcher do you use?

<img width="243" alt="image" src="https://user-images.githubusercontent.com/98573273/190902935-3a306120-7284-4411-8572-9329dcc0da3f.png">
THIS ONE

**Comment by FalsePattern** [comment]
@iamsoNewBee you're using a -dev jar, use the regular jar

**Comment by quentin452** [comment]
maybe this launcher does not generate fml-client-latest.log

**Comment by quentin452** [comment]
https://github.com/FalsePattern/FalsePatternLib/releases/download/0.10.10/falsepatternlib-mc1.7.10-0.10.10.jar you need to use this

**Comment by iamsoNewBee** [comment]
oops....XD
