### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by StrangeMan1580** [FalsePattern/FalsePatternLib#31]
[latest.log](https://github.com/FalsePattern/FalsePatternLib/files/12690408/latest.log)
The game doesn't load with any version of FalsePatternLib after 0.11.1 with error "java.lang.SecurityException: SHA-256 digest error for assets/forge/lang/ru_RU.lang", because I directly modified the russian localization file in forge.jar by adding some strings (yeah, that wasn't very clever), but is it really necessary to check localization files in the forge.jar?

**Comment by FalsePattern** [comment]
Not caused by FalsePatternLib.
