### ISSUE TITLE
Crash on startup with 1.0.0-pre1 when a modpack have .zip mods

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/FalsePatternLib#32]
note : the crash seem only to appear with .zip mods

logs : 

[latest.log](https://github.com/FalsePattern/FalsePatternLib/files/13401284/latest.log)

**Comment by quentin452** [comment]
it seem that the bug appear also with jar mods

**Comment by FalsePattern** [comment]
Should be fixed in preview 2

**Comment by quentin452** [comment]
Seem to be fixed , thx
