### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/FalsePatternLib#33]
Title, versions below.

![image](https://github.com/FalsePattern/FalsePatternLib/assets/51277766/9cf0a0f7-04dc-4a3e-a981-a4d3dc0b950f)

No crash report file is created, but is in the log file.

https://pastebin.com/5Yiqi0uL

**Comment by FalsePattern** [comment]
Not caused by FalsePatternLib.
