### ISSUE TITLE
No Class Def Found: LoggerFactory from ViaForge

### ISSUE THREAD

**Issue by MrSliTraP2716Lua** [FalsePattern/FalsePatternLib#36]
Crashed with ViaForge (backported for 1.7.10)
short crashlog:
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

file application:
[crash-2024-05-29_09.47.37-client.txt](https://github.com/FalsePattern/FalsePatternLib/files/15480088/crash-2024-05-29_09.47.37-client.txt)

thx
Slickey

**Comment by FalsePattern** [comment]
Why was this reported here? The crashlog says nothing about FalsePatternLib.
