### ISSUE TITLE
[Bug]: Disabling update checker (ENABLE_UPDATE_CHECKER=false) crashes the game

### ISSUE THREAD

**Issue by tyrael93** [FalsePattern/FalsePatternLib#4]
### Game log

[fml-client-latest.log](https://github.com/FalsePattern/FalsePatternLib/files/8984463/fml-client-latest.log)

### Description

Disabling the update checker (even with only falsepatternlib and spongemixins), crashes the game.
https://paste.ee/p/SndXo

**Comment by FalsePattern** [comment]
Fixed in 0.9.1
