### ISSUE TITLE
Add option to use a shared directory for dependencies

### ISSUE THREAD

**Issue by makamys** [FalsePattern/FalsePatternLib#7]
### The problem
Currently, if a mod requests a dependency, it will always be stored inside `<instance dir>/mods/falsepattern`. This means if the same dependency is requested in multiple instances, a copy of it will be stored in each instance. This can cause a lot of disk space to be wasted if you have many instances. For example, [ArchaicFix](https://github.com/embeddedt/ArchaicFix) depends on fastutil, a 22 MB library. I already have 3 copies of it on my computer in `falsepattern` directories, and I am certain this number will keep growing.

### Suggestion
In [AssetDirector](https://github.com/makamys/MCLib/wiki/AssetDirector), I have outlined a standard for specifying the location of a shared data directory for Minecraft instances. One way to solve the problem would be to follow it:
* If the `minecraft.sharedDataDir` JVM flag is set, `<minecraft.sharedDataDir>/mods/falsepattern` could be used
* If the `MINECRAFT_SHARED_DATA_DIR` environmental variable is set, `$MINECRAFT_SHARED_DATA_DIR/mods/falsepattern` could be used

**Comment by FalsePattern** [comment]
Added this to the mod, available in 0.9.4+
