### ISSUE TITLE
Check integrity of dependencies after downloading them

### ISSUE THREAD

**Issue by makamys** [FalsePattern/FalsePatternLib#9]
Sometimes a dependency can fail to get downloaded correctly, which will cause mods using that dependency to fail to load until the corrupted file is deleted manually. Most (all?) Maven repositories host `.md5` and `.sha1` files which could be used to verify that the download was correct.

This issue was encountered by a user of ArchaicFix. They had an incomplete download of fastutil that was 8 MB instead of the expected 22 MB. The issue was fixed by deleting the file and letting it download again. The log of the failed launch can be found [here](https://cdn.discordapp.com/attachments/993717703032447016/997563804458160339/fml-client-latest.log), and the relevant Discord messages [here](https://discord.com/channels/741043720241152001/993717703032447016/997563589256810496).

**Comment by FalsePattern** [comment]
Added this to the mod, available in 0.9.4+. It also tries sha512 and sha256 checksums before sha1 and md5, just for completeness' sake.
